// Quokkaroo — Australian city knowledge base.
// Everything the city panel shows lives here: facts, copy, images, migration angle.
// lat/lon drive the globe beacons; `key` matches assets/img/cities/<key>-N.jpg.

export const CITIES = [
  {
    key: 'sydney',
    name: 'Sydney',
    state: 'New South Wales',
    lat: -33.87, lon: 151.21,
    tagline: 'Australia’s global city — harbour, beaches and big careers.',
    intro: 'Sydney is Australia’s largest city and its commercial engine, wrapped around one of the most beautiful harbours on Earth. It’s where the Opera House, the Harbour Bridge and a hundred beaches meet the headquarters of the country’s biggest employers.',
    why: 'Life in Sydney runs between salt water and skyline. Mornings start with a swim at an ocean pool, ferries replace freeways for many commutes, and weekends stretch from the Northern Beaches to the Blue Mountains an hour west. It’s Australia’s most international city — over 40% of Sydneysiders were born overseas — so whatever home tastes like, you’ll find it here.',
    work: 'The deepest job market in the country. Finance and professional services cluster in the CBD and Barangaroo, tech around Tech Central, and the health network is enormous — Royal Prince Alfred, Westmead, St Vincent’s and a constant demand for ICU, theatre and mental-health nurses, registrars and NUMs. Aged and disability care, ICT and FMCG roles are perennially short-staffed.',
    sectors: ['Health & Hospitals', 'ICT', 'Aged & Disability Care', 'FMCG'],
    lifestyle: 'More than 100 beaches, year-round outdoor living, world-class food from Cabramatta noodles to Surry Hills fine dining. The trade-off is cost: Sydney is Australia’s most expensive city for housing, which is why many migrants start here and some settle in its outer rings — or use it as the benchmark to compare every other city below.',
    migration: 'Sydney is one of the three major metros, so it sits outside Australia’s “regional” visa concessions — most skilled migrants arrive on employer-sponsored or points-tested visas. Strong salaries help offset the famous housing costs.',
    facts: [
      { label: 'Population', value: '~5.5 million' },
      { label: 'Time zone', value: 'AEST (UTC+10)' },
      { label: 'Summer', value: '19–27°C' },
      { label: 'Winter', value: '8–17°C' },
      { label: 'Known for', value: 'Harbour, beaches, big business' },
    ],
    images: [
      { src: 'assets/img/cities/sydney-1.jpg', caption: 'Sydney Harbour' },
      { src: 'assets/img/australia/sydney.jpg', caption: 'Opera House & Harbour Bridge' },
      { src: 'assets/img/cities/sydney-2.jpg', caption: 'Beach life, Sydney style' },
      { src: 'assets/img/australia/bondi.jpg', caption: 'Bondi Beach' },
    ],
  },
  {
    key: 'melbourne',
    name: 'Melbourne',
    state: 'Victoria',
    lat: -37.81, lon: 144.96,
    tagline: 'The cultural capital — coffee, sport, art and serious healthcare.',
    intro: 'Melbourne is Australia’s second city by a whisker and its undisputed capital of culture: laneway coffee, live music, street art, and the world’s most sport-obsessed calendar from the Australian Open to the AFL Grand Final.',
    why: 'Melbourne is built for living well at street level. Trams glide past Victorian arcades into leafy suburbs, each with its own village feel — Greek in Oakleigh, Vietnamese in Footscray, Italian in Carlton. The weather famously does four seasons in one day, and locals will tell you that’s part of the charm. It is consistently ranked among the world’s most liveable cities.',
    work: 'A healthcare and research powerhouse — the Parkville biomedical precinct, the Royal Melbourne, the Alfred and Monash Health recruit constantly for nurses, registrars and allied health. Education, ICT and a large FMCG/logistics sector round out a job market nearly as deep as Sydney’s, usually with gentler rents.',
    sectors: ['Health & Hospitals', 'Allied Health', 'ICT', 'FMCG'],
    lifestyle: 'Coffee culture taken as seriously as anywhere on Earth, 240+ live music venues, beaches along Port Phillip Bay and the Great Ocean Road a day-trip away. Housing is expensive but meaningfully cheaper than Sydney, with excellent public transport across the suburbs.',
    migration: 'Like Sydney and Brisbane, Melbourne is a major metro outside the regional visa concessions — but Victoria runs active state-nomination programs for health, allied health and ICT skills.',
    facts: [
      { label: 'Population', value: '~5.4 million' },
      { label: 'Time zone', value: 'AEST (UTC+10)' },
      { label: 'Summer', value: '16–26°C' },
      { label: 'Winter', value: '7–14°C' },
      { label: 'Known for', value: 'Coffee, culture, liveability' },
    ],
    images: [
      { src: 'assets/img/cities/melbourne-1.jpg', caption: 'Melbourne on the Yarra' },
      { src: 'assets/img/australia/melbourne.jpg', caption: 'Princes Bridge at night' },
      { src: 'assets/img/cities/melbourne-2.jpg', caption: 'The famous laneways' },
    ],
  },
  {
    key: 'brisbane',
    name: 'Brisbane',
    state: 'Queensland',
    lat: -27.47, lon: 153.03,
    tagline: 'Sunshine-state capital on the rise — host of the 2032 Olympics.',
    intro: 'Brisbane is Australia’s fastest-growing capital: a relaxed, subtropical river city that has hit its stride, with the 2032 Olympic and Paralympic Games driving a decade of investment in hospitals, transport and homes.',
    why: 'Brisbane gives you big-city careers at a friendlier pace and price than Sydney or Melbourne. Life happens outdoors almost year-round — riverside markets, South Bank’s inner-city lagoon, and weekends split between the Gold Coast an hour south and the Sunshine Coast an hour north. Winters are warm enough for the beach.',
    work: 'Queensland Health is one of the state’s biggest employers, with major recruiting at the Royal Brisbane, Princess Alexandra and the Queensland Children’s Hospital. Mining and resources companies run their corporate and engineering operations from the CBD, and Olympics-driven construction, ICT and logistics demand keeps climbing.',
    sectors: ['Health & Hospitals', 'Mining & Resources', 'ICT', 'Aged & Disability Care'],
    lifestyle: '~280 sunny days a year, an outdoor café culture along the river, and some of the best value housing of the big three east-coast capitals. The lifestyle pitch is simple: real career, real backyard, beach within an hour.',
    migration: 'A major metro for visa purposes, but the rest of Queensland around it is regional — many migrants land a Brisbane role after starting in regional Queensland, or use state nomination for health and engineering skills.',
    facts: [
      { label: 'Population', value: '~2.8 million' },
      { label: 'Time zone', value: 'AEST (UTC+10, no DST)' },
      { label: 'Summer', value: '21–30°C' },
      { label: 'Winter', value: '10–22°C' },
      { label: 'Known for', value: 'Sunshine, growth, 2032 Games' },
    ],
    images: [
      { src: 'assets/img/cities/brisbane-1.jpg', caption: 'Brisbane and the Story Bridge' },
      { src: 'assets/img/cities/brisbane-2.jpg', caption: 'South Bank parklands' },
    ],
  },
  {
    key: 'perth',
    name: 'Perth',
    state: 'Western Australia',
    lat: -31.95, lon: 115.86,
    tagline: 'The sunniest capital — gateway to the mining boom and Indian Ocean beaches.',
    intro: 'Perth is Australia’s western capital: the sunniest big city in the country, set between the Swan River and a string of white Indian Ocean beaches, and the home base of the resources industry that powers the national economy.',
    why: 'Perth offers the strongest pay-to-cost ratio of any Australian capital. Mining money flows through the city, houses are markedly cheaper than the east coast, and the lifestyle is pure West Coast: sunset swims at Cottesloe, Kings Park bigger than Central Park, Rottnest Island — home of the quokka itself — a short ferry away. For South Africans it has a familiar feel and the gentlest jet lag: closer to Johannesburg time than Sydney is.',
    work: 'Mining and resources dominate — diesel mechanics, engineers, surveyors, electricians and health & safety advisors are in chronic shortage, both in Perth offices and on fly-in-fly-out rosters. The health system (Fiona Stanley, Sir Charles Gairdner, Perth Children’s) recruits internationally every year, and aged care and ICT demand runs deep.',
    sectors: ['Mining & Resources', 'Health & Hospitals', 'Aged & Disability Care', 'ICT'],
    lifestyle: 'Around 3,000 hours of sunshine a year — Australia’s sunniest capital. Beaches without crowds, the Margaret River wine region down south, and a laid-back, family-first pace. The catch people mention is isolation; the answer locals give is that everything you need is already here.',
    migration: 'Perth is classed as REGIONAL for skilled migration — extra points, access to 491/494 regional visas and dedicated WA state-nomination streams. One of the easiest big-city pathways in the country.',
    facts: [
      { label: 'Population', value: '~2.4 million' },
      { label: 'Time zone', value: 'AWST (UTC+8)' },
      { label: 'Summer', value: '18–31°C' },
      { label: 'Winter', value: '8–19°C' },
      { label: 'Known for', value: 'Sunshine, mining careers, beaches' },
    ],
    images: [
      { src: 'assets/img/cities/perth-1.jpg', caption: 'Perth across the Swan River' },
      { src: 'assets/img/australia/perth.jpg', caption: 'The city at dusk' },
      { src: 'assets/img/cities/perth-2.jpg', caption: 'Indian Ocean beach life' },
      { src: 'assets/img/australia/quokka.jpg', caption: 'Rottnest Island — home of the quokka' },
    ],
  },
  {
    key: 'adelaide',
    name: 'Adelaide',
    state: 'South Australia',
    lat: -34.93, lon: 138.6,
    tagline: 'The 20-minute city — festivals, wine country and regional visa gold.',
    intro: 'Adelaide is the capital nobody regrets: a gracious, planned city ringed by parklands, twenty minutes from both the beach and the vines, with Australia’s most affordable big-city living and a booming defence and health economy.',
    why: 'Adelaide runs on the “20-minute rule” — work, school, beach and the Adelaide Hills are all about twenty minutes from anywhere. It hosts the southern hemisphere’s biggest arts festival (Adelaide Fringe), sits next to world-famous wine regions (Barossa, McLaren Vale), and house prices that make east-coast arrivals do a double-take. It is regularly voted among the world’s most liveable cities.',
    work: 'Defence shipbuilding at Osborne (submarines and frigates) is creating thousands of long-term engineering and trades jobs. The new Royal Adelaide Hospital anchors a major biomed precinct, aged care is a huge employer across the state, and the Tonsley innovation district is growing ICT and advanced manufacturing fast.',
    sectors: ['Health & Hospitals', 'Aged & Disability Care', 'ICT', 'Mining & Resources'],
    lifestyle: 'Mediterranean climate, beaches like Glenelg a tram ride from town, 700+ cellar doors within an hour, and the lowest cost of living of the mainland capitals. Families love the space; foodies stay for the produce.',
    migration: 'All of South Australia — including Adelaide — is classed as REGIONAL for skilled migration. That means extra points, 491/494 visa access and generous state nomination. Pound for pound, one of the best-value migration destinations in Australia.',
    facts: [
      { label: 'Population', value: '~1.5 million' },
      { label: 'Time zone', value: 'ACST (UTC+9:30)' },
      { label: 'Summer', value: '17–29°C' },
      { label: 'Winter', value: '8–16°C' },
      { label: 'Known for', value: 'Festivals, wine, affordability' },
    ],
    images: [
      { src: 'assets/img/cities/adelaide-1.jpg', caption: 'Adelaide on the Torrens' },
      { src: 'assets/img/cities/adelaide-2.jpg', caption: 'Beaches & wine country at the door' },
    ],
  },
  {
    key: 'goldcoast',
    name: 'Gold Coast',
    state: 'Queensland',
    lat: -28.0, lon: 153.43,
    tagline: '57 kilometres of beach — Australia’s lifestyle capital.',
    intro: 'The Gold Coast is Australia’s sixth-largest city and its most famous playground: 57 km of surf beaches backed by a real, fast-growing economy in health, construction and tourism — an hour from Brisbane.',
    why: 'This is the city people picture when they dream of Australia: morning surf at Burleigh Heads, breakfast in boardshorts, rainforest hinterland twenty minutes inland. But it’s no longer just a holiday strip — the Gold Coast is one of the country’s fastest-growing cities, with serious hospitals, three universities and a young, international population.',
    work: 'Gold Coast University Hospital is one of Queensland’s largest teaching hospitals and recruits nurses, midwives and registrars internationally. Aged and disability care demand is enormous given the demographics, construction is in permanent boom, and health-tech and ICT are growing out of the Lumina precinct.',
    sectors: ['Health & Hospitals', 'Aged & Disability Care', 'Allied Health', 'FMCG'],
    lifestyle: 'Around 300 sunny days a year, surf culture as the default lifestyle, theme parks for the kids and a hinterland of waterfalls and rainforest. More affordable than Sydney, livelier than most regional cities.',
    migration: 'The Gold Coast is classed as REGIONAL for skilled migration despite its size — regional points, 491/494 eligibility and employer concessions apply. A genuine big-beach-city with regional-visa advantages.',
    facts: [
      { label: 'Population', value: '~750,000' },
      { label: 'Time zone', value: 'AEST (UTC+10, no DST)' },
      { label: 'Summer', value: '21–29°C' },
      { label: 'Winter', value: '9–21°C' },
      { label: 'Known for', value: 'Surf, sunshine, growth' },
    ],
    images: [
      { src: 'assets/img/cities/goldcoast-1.jpg', caption: 'Surfers Paradise' },
      { src: 'assets/img/australia/gold-coast.jpg', caption: 'The Gold Coast skyline' },
      { src: 'assets/img/cities/goldcoast-2.jpg', caption: 'Burleigh Heads' },
    ],
  },
  {
    key: 'canberra',
    name: 'Canberra',
    state: 'Australian Capital Territory',
    lat: -35.28, lon: 149.13,
    tagline: 'The capital — highest salaries, top schools, four real seasons.',
    intro: 'Canberra is Australia’s purpose-built capital: a calm, green, planned city of lakes and museums with the highest average incomes in the country and a quality of life that routinely tops national surveys.',
    why: 'Canberra is the quiet achiever. Commutes average fifteen minutes, schools and the ANU rank among Australia’s best, and the city sits inside nature — kangaroos on the golf course, snowfields two hours away, vineyards twenty minutes out. It’s the only Australian city with four genuine seasons, including a postcard autumn.',
    work: 'Government is the anchor employer, which creates Australia’s strongest demand for ICT, cyber-security and policy professionals. Canberra Hospital and a growing private health sector recruit steadily, and the public-sector gravity means salaries here are the highest in the nation on average.',
    sectors: ['ICT', 'Health & Hospitals', 'Allied Health', 'Aged & Disability Care'],
    lifestyle: 'Lake Burley Griffin for morning rows, the national galleries and museums for weekends, hot-air balloons over Parliament at dawn. Family-friendly, safe and uncrowded — with crisp winters Canberrans wear as a badge of honour.',
    migration: 'The ACT is classed as REGIONAL for skilled migration and runs its own popular nomination program (the Canberra Matrix) — a well-trodden pathway for ICT and health professionals.',
    facts: [
      { label: 'Population', value: '~480,000' },
      { label: 'Time zone', value: 'AEST (UTC+10)' },
      { label: 'Summer', value: '13–28°C' },
      { label: 'Winter', value: '0–12°C' },
      { label: 'Known for', value: 'Top salaries, education, space' },
    ],
    images: [
      { src: 'assets/img/cities/canberra-1.jpg', caption: 'The national capital' },
      { src: 'assets/img/cities/canberra-2.jpg', caption: 'Lake Burley Griffin' },
    ],
  },
  {
    key: 'newcastle',
    name: 'Newcastle',
    state: 'New South Wales',
    lat: -32.93, lon: 151.78,
    tagline: 'Big-city jobs, small-city commute — two hours north of Sydney.',
    intro: 'Newcastle is NSW’s second city: a former steel town reborn as one of Australia’s coolest coastal cities, with working beaches, a working port and a fraction of Sydney’s prices two hours up the coast.',
    why: 'Novocastrians surf before work — the city has six beaches inside its limits, including the famous ocean baths. The vibe is creative and unpretentious: warehouse breweries, a thriving arts scene, and the Hunter Valley wine country forty minutes inland. You get coastal-city life with a real economy underneath it.',
    work: 'John Hunter Hospital is the major trauma centre for northern NSW and a big international recruiter of nurses and specialists. The Port of Newcastle, energy transition projects, engineering and the University of Newcastle anchor a diverse job market; aged care demand across the Hunter is constant.',
    sectors: ['Health & Hospitals', 'Aged & Disability Care', 'Mining & Resources', 'ICT'],
    lifestyle: 'Beach-town mornings and city amenities, median house prices roughly half of Sydney’s, and a renowned live-music heritage. Sydney is two hours by train when you want it — most people find they rarely do.',
    migration: 'Newcastle (with Lake Macquarie) is classed as REGIONAL for skilled migration — regional points and 491/494 visa access in a city of half a million people on the coast.',
    facts: [
      { label: 'Population', value: '~500,000' },
      { label: 'Time zone', value: 'AEST (UTC+10)' },
      { label: 'Summer', value: '19–26°C' },
      { label: 'Winter', value: '9–17°C' },
      { label: 'Known for', value: 'Surf beaches, value, reinvention' },
    ],
    images: [
      { src: 'assets/img/cities/newcastle-1.jpg', caption: 'Nobbys Head, Newcastle' },
      { src: 'assets/img/cities/newcastle-2.jpg', caption: 'Ocean baths & beach culture' },
    ],
  },
  {
    key: 'hobart',
    name: 'Hobart',
    state: 'Tasmania',
    lat: -42.88, lon: 147.33,
    tagline: 'Island capital — wilderness, art and Australia’s cleanest air.',
    intro: 'Hobart is Australia’s southernmost capital: a harbour city of sandstone and fishing boats beneath kunanyi/Mount Wellington, where world-class wilderness starts at the end of the street and the MONA gallery rewrote what a small city can be.',
    why: 'Hobart trades scale for soul. Saturday is Salamanca Market, Sunday is a mountain or a beach with nobody on it, and dinner is whatever came off the boats that morning. Tasmania has Australia’s cleanest air and some of its most affordable coastal living — and the slower pace is exactly the point.',
    work: 'Health and aged care are Tasmania’s biggest recruiters — the Royal Hobart Hospital and the aged-care network draw heavily on international staff. Antarctic and marine science (Hobart is Australia’s Antarctic gateway), tourism and a fast-growing food and beverage export sector round it out. Veterinarians are in genuine shortage statewide.',
    sectors: ['Health & Hospitals', 'Aged & Disability Care', 'Veterinary', 'Allied Health'],
    lifestyle: 'Four crisp seasons, southern lights in winter, Australia’s best cool-climate wine and whisky, and a creative community punching far above its size. Snow on the mountain some mornings; beach swims (brave ones) in summer.',
    migration: 'All of Tasmania is classed as REGIONAL for skilled migration, and the state runs one of Australia’s most accessible nomination programs — a favourite first landing point for health and care workers.',
    facts: [
      { label: 'Population', value: '~255,000' },
      { label: 'Time zone', value: 'AEST (UTC+10)' },
      { label: 'Summer', value: '12–22°C' },
      { label: 'Winter', value: '5–12°C' },
      { label: 'Known for', value: 'Wilderness, MONA, clean air' },
    ],
    images: [
      { src: 'assets/img/cities/hobart-1.jpg', caption: 'Hobart beneath kunanyi' },
      { src: 'assets/img/cities/hobart-2.jpg', caption: 'Salamanca & the waterfront' },
    ],
  },
  {
    key: 'darwin',
    name: 'Darwin',
    state: 'Northern Territory',
    lat: -12.46, lon: 130.84,
    tagline: 'The tropical frontier — Asia on the doorstep, opportunity everywhere.',
    intro: 'Darwin is Australia’s tropical northern capital: a young, multicultural frontier city closer to Bali than to Sydney, where defence, energy and a chronic skills shortage make it one of the easiest places in the country to build a new life fast.',
    why: 'Darwin feels like nowhere else in Australia — outdoor cinemas in the dry season, Mindil Beach sunset markets, crocodile country an hour away in Kakadu and Litchfield. The community is small enough that newcomers are noticed and welcomed, and career progression that would take a decade down south can happen in two years.',
    work: 'Royal Darwin Hospital serves the entire Top End and recruits internationally across nearly every specialty. Defence is expanding its northern presence, LNG and minerals projects need trades and engineers, and aged care, disability and veterinary roles go unfilled for months — employers here genuinely compete for skilled migrants.',
    sectors: ['Health & Hospitals', 'Mining & Resources', 'Aged & Disability Care', 'Veterinary'],
    lifestyle: 'Endless warmth (25–33°C year-round), two seasons — wet and dry — and a barefoot, multicultural ease: more than 60 nationalities at the markets. The highest salaries-to-cost ratio in northern Australia.',
    migration: 'The whole Northern Territory is REGIONAL for skilled migration, and the NT runs its own Designated Area Migration Agreement (DAMA) with concessions on age, English and salary for dozens of occupations. Often the fastest visa pathway in the country.',
    facts: [
      { label: 'Population', value: '~150,000' },
      { label: 'Time zone', value: 'ACST (UTC+9:30, no DST)' },
      { label: 'Dry season', value: '21–32°C, May–Oct' },
      { label: 'Wet season', value: '25–33°C, Nov–Apr' },
      { label: 'Known for', value: 'Tropics, opportunity, Kakadu' },
    ],
    images: [
      { src: 'assets/img/cities/darwin-1.jpg', caption: 'Darwin’s waterfront' },
      { src: 'assets/img/cities/darwin-2.jpg', caption: 'Mindil Beach sunset' },
    ],
  },
  {
    key: 'cairns',
    name: 'Cairns',
    state: 'Queensland',
    lat: -16.92, lon: 145.77,
    tagline: 'Where the rainforest meets the Reef — tropical living, real demand.',
    intro: 'Cairns is the capital of Tropical North Queensland: the gateway city to the Great Barrier Reef and the Daintree — the world’s oldest rainforest — with a healthcare and services economy that serves the whole far north.',
    why: 'Living in Cairns means the Reef is your weekend and the rainforest is your backdrop. The Esplanade lagoon anchors a relaxed, outdoorsy city where winter means 26 degrees, and the airport connects you straight to Asia and every Australian capital. It’s the tropics with infrastructure.',
    work: 'Cairns Hospital is the referral centre for the entire far north — nurses, midwives, registrars and allied health professionals are recruited internationally every year. Tourism and hospitality power the city, marine science and agriculture (sugar, tropical fruit) need specialists, and aged care and veterinary demand outstrips supply.',
    sectors: ['Health & Hospitals', 'Aged & Disability Care', 'Veterinary', 'Allied Health'],
    lifestyle: 'Reef trips, waterfall circuits on the Atherton Tablelands, Kuranda rainforest villages, and a genuinely multicultural small city. Housing costs are far below the capitals; the lifestyle premium is the whole point.',
    migration: 'Cairns is REGIONAL for skilled migration with 491/494 access and regional points — and far-north employers are among the most motivated sponsors in Queensland.',
    facts: [
      { label: 'Population', value: '~155,000' },
      { label: 'Time zone', value: 'AEST (UTC+10, no DST)' },
      { label: 'Summer', value: '24–31°C' },
      { label: 'Winter', value: '18–26°C' },
      { label: 'Known for', value: 'The Reef, the Daintree, the tropics' },
    ],
    images: [
      { src: 'assets/img/cities/cairns-1.jpg', caption: 'Cairns Esplanade' },
      { src: 'assets/img/australia/reef.jpg', caption: 'The Great Barrier Reef' },
      { src: 'assets/img/cities/cairns-2.jpg', caption: 'The Daintree — the world’s oldest rainforest' },
    ],
  },
  {
    key: 'townsville',
    name: 'Townsville',
    state: 'Queensland',
    lat: -19.26, lon: 146.82,
    tagline: 'Northern Australia’s working capital — 320 days of sunshine.',
    intro: 'Townsville is the largest city in northern Australia: a garrison, port and university city on the dry tropical coast, with Magnetic Island twenty minutes offshore and one of the most reliable job markets in regional Australia.',
    why: 'Townsville is the practical choice that surprises people. The Strand beachfront runs the length of the city beneath Castle Hill’s pink granite, the climate is famously sunny (around 320 days a year), and salaries stretch much further than down south. Magnetic Island — koalas, beaches, walking trails — is a commuter ferry away.',
    work: 'Townsville University Hospital is the tertiary centre for all of northern Queensland and recruits internationally across nursing, medicine and allied health. Lavarack Barracks makes defence a huge economic anchor, the port and minerals processing need trades and engineers, and James Cook University drives research and education jobs.',
    sectors: ['Health & Hospitals', 'Mining & Resources', 'Aged & Disability Care', 'Veterinary'],
    lifestyle: 'Dry-tropics sunshine nearly every day, an affordable family lifestyle, reef and island weekends, and a friendly, no-airs community where skilled newcomers integrate fast.',
    migration: 'Townsville is REGIONAL for skilled migration and runs its own DAMA with occupation concessions — one of the most welcoming visa environments anywhere in Australia.',
    facts: [
      { label: 'Population', value: '~200,000' },
      { label: 'Time zone', value: 'AEST (UTC+10, no DST)' },
      { label: 'Summer', value: '24–31°C' },
      { label: 'Winter', value: '14–25°C' },
      { label: 'Known for', value: 'Sunshine, defence, Magnetic Island' },
    ],
    images: [
      { src: 'assets/img/cities/townsville-1.jpg', caption: 'Townsville & Castle Hill' },
      { src: 'assets/img/cities/townsville-2.jpg', caption: 'Magnetic Island' },
    ],
  },
];
